repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (system)
        entry: ruff check .
        language: system
        types: [python]

      - id: black
        name: black (system)
        entry: black .
        language: system
        types: [python]
