repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (system)
        entry: ruff check --fix
        language: system
        types: [python]
        

      - id: black
        name: black (system auto-format)
        entry: black
        language: system
        types: [python]
        args: ["--quiet"]
